version: '3.8'

services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
      JWT_SECRET: a6b8e4fdf99f37c8e77f65a7db31e4d78e4d0126c5b98d2eb5f4c9db2d205b99
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:dev"

  postgres:
    image: postgres:14.2
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
